spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 8883
  context-path: /pay
  tomcat:
    uri-encoding: utf-8

eureka:
  instance:
    metadata-map:
      cluster: BC-THIRD-PAY


